<?php
/**
 * Created by PhpStorm.
 * User: onela
 * Date: 11.05.2019
 * Time: 12:37
 */

namespace app\models;


use yii\base\Model;

class CartUserForm extends Model
{
    public $phone;
    public $adr;

    public function init()
    {
        $this->phone = \Yii::$app->user->identity['phone'];
        $this->adr = \Yii::$app->user->identity['adr'];
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules() {
        return [
            [
                ['adr', 'phone'],
                'required',
                'message' => 'Заполните поле'
            ],
        ];
    }

    public function attributeLabels() {
        return [
            'phone' => 'Телефон',
            'adr' => 'Адрес',
        ];
    }
}