<?php

namespace app\models;

use yii\base\Object;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

class User extends ActiveRecord implements IdentityInterface
{
    const ROLE_ADMIN = 'admin';

    public static function tableName(){
        return 'user';
    }

    public function rules()
    {
        return [
            [['login', 'password', 'email', 'phone'], 'required'],
            [['role', 'adr'], 'string'],
            [['login', 'email', 'name'], 'string', 'max' => 50],
            [['password', 'phone'], 'string', 'max' => 255],
            [['email'], 'unique'],
            [['login'], 'unique'],
        ];
        // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'login' => 'Логин',
            'password' => 'Пароль',
            'auth_key' => 'Auth Key',
            'email' => 'Email',
            'role' => 'Роль',
            'name' => 'Имя',
            'phone' => 'Телефон',
            'adr' => 'Адрес',
        ];
    }
    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {

    }

    public static function findByUsername($login)
    {
        return static::findOne(['login' => $login]);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->auth_key === $auth_key;
    }

    public function validatePassword($password)
    {
        return \Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }

    public function generateAuthKey(){
        $this->auth_key = \Yii::$app->getSecurity()->generateRandomString();

    }

    public static function isUserAdmin($username)
    {
        if (static::findOne(['login' => $username, 'role' => self::ROLE_ADMIN]))
        {
            $_SESSION['user']['admin'] = true;
            return true;
        } else {
            return false;
        }
    }
}
